### ISSUE TITLE
[Bug] Email verification step is a dead end

### ISSUE THREAD

**Issue by pdehaan** [mozilla-rally/rally-web-platform#497]
**Describe the bug**

**To Reproduce**
1. Signed up for a new Rally account
2. Verified my email

**Actual results**

> ### Your email has been verified
> You can now sign in with your new account

**Expected behavior**

The verification screen should have a link or something to sign in with my freshly verified account.

**Screenshots**
If applicable

**Browser / OS:**
 
**Additional context**

**Comment by rhelmer** [comment]
These are very limited because we use Firebases' default email action handlers, I just filed https://github.com/mozilla-rally/rally-web-platform/issues/507 which covers creating our own handlers for these functions. This would allow us to have full control over the templates used in outbound email and the web handlers.
