### ISSUE TITLE
Firebase stage and prod config

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#56]
As a Rally engineer, I need configurations for stage and prod Firebase environments.

Jason Thomas is on parental leave after 8/13.

**Comment by rhelmer** [comment]
Jason brought a staging Firebase instance up, @hamilton and I have access to change it. This and prod work is being tracked in https://mozilla-hub.atlassian.net/browse/DSRE-112 - however I don't want to go fiddle with it yet, since Jason is going out starting next week, and handing off to a new person, so I'd like to make sure we get the change management right. We have our dev instance we can continue to use in the meantime, where it's fine to make changes ourselves.

**Comment by rhelmer** [comment]
There's a GCP slack with our support folks that I've been invited to as well, I'll participate there and see if we can folks can give us useful feedback on our plans.

**Comment by rhelmer** [comment]
Staging: https://github.com/mozilla-rally/rally-web-platform/pull/150

**Comment by rhelmer** [comment]
Oops, sorry meant to leave this open until both prod and stage are up.

**Comment by jepstein** [comment]
We will need reengage with SRE, probably Jason Thomas, but starting with SuAnn.
Achyuth is no longer around.
